### ISSUE TITLE
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)

### ISSUE THREAD

**Issue by agaqueiroz** [remcohaszing/mermaid-isomorphic#11]
Hi everyone, 

I've tried rehype-mermaid with this configuration:

```javascript
import parse from 'remark-parse';
import format from 'rehype-format';
import raw from 'rehype-raw';
import stringify from 'rehype-stringify';
import pluginMarkdownToHtml from 'remark-rehype';
import highlight from 'rehype-highlight';
import rehypeMermaid from 'rehype-mermaid';
import { unified } from 'unified';

export default async function markdownToHtml(markdown: string) {                             
  const result = await unified().use(parse) // the parser to use after process()
                                .use(pluginMarkdownToHtml, {allowDangerousHtml: true}) // use rehype HTML ecosystem
                                .use(rehypeMermaid, { strategy: 'inline-svg'})
                                .use(raw)
                                .use(highlight) // add classname for highlight code
                                .use(format)
                                .use(stringify) // the final step
                                .process(markdown);
  return result.toString();
}
```
But, the Server Side Rendering process logs this error:

` ⚠ ./node_modules/mermaid-isomorphic/dist/mermaid-isomorphic.js
Critical dependency: Accessing import.meta directly is unsupported (only property access or destructuring is supported)`

In the client side, the server sends 500 error and nothing is rendered.

It seems that the _import.meta_ is used while it shouldn't be.

**Comment by remcohaszing** [comment]
This looks like an issue with your framework. Where do the logs come from?

**Comment by agaqueiroz** [comment]
Yes, it seems that the error comes from the SWC, the NextJS compiler. 

First, the logs comes from the default console. I was customizing the NextJS [Blog Starter Kit](https://vercel.com/templates/next.js/blog-starter-kit), with NextJS 15.1.2. I'd changed the markdownToHtml.ts with the code above. The full console log is in [console.log](https://github.com/user-attachments/files/18223809/console.log).

Also, I'd changed the dependency from
```javascript
import { unified } from 'unified';
```
to
```javascript
import { rehype } from 'rehype';
```
But the result is the same.

Furthermore, into [mermaid-isomorphic.ts](https://github.com/remcohaszing/mermaid-isomorphic/blob/main/src/mermaid-isomorphic.ts) code, it seems nothing is wrong with import.meta call, based on NodeJS [docs](https://nodejs.org/docs/latest/api/esm.html).

In the end, in a similar [case 1](https://github.com/web-infra-dev/rsbuild/issues/1585) and [case 2](https://github.com/swc-project/swc/issues/2615) points to the compiler that should support the import.meta. I've changed the default SWC compiler to [Babel compiler](https://nextjs.org/docs/pages/building-your-application/configuring/babel), but other errors popped up. I'll try workarounds along this path. Thanks!

**Comment by AugustinMauroy** [comment]
Hey someone had found solution about this ??? because we had same issue on nodejs.org

**Comment by remcohaszing** [comment]
Cool to hear you want to use this for the Node.js docs ♥️

I suspect Next.js doesn’t like the use of `import.meta.resolve()`. You can modify `mermaid-isomorphic` in your `node_modules` to see if that makes a difference. For example assign `import.meta.resolve` to a variable before calling it.

**Comment by AugustinMauroy** [comment]
> I suspect Next.js doesn’t like the use of import.meta.resolve(). You can modify mermaid-isomorphic in your node_modules to see if that makes a difference. For example assign import.meta.resolve to a variable before calling it.

that's because webpack can't work with ` import.meta.resolve()`. I didn't found any solution for now

**Comment by remcohaszing** [comment]
Unfortunately `mermaid-isomorphic` has to load an HTML file using the `file://` protocol. I tried a base64 encoded HTML document, but that causes permission issues in the Playwright browser.

**Comment by remcohaszing** [comment]
Why do you use a custom compile function? I think this issue goes away if you use `@next/mdx`.

**Comment by qweasdzxcpkh** [comment]
Hi, i am facing the same issue.
my environment: nextjs@14 react-markdown rehype-mermaid->[this repo]
my solution(maybe interim) is: use client component, and config the webpack alias with this package to broswer version:
```js
// next.config.mjs
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
webpack(config) {
  [...]
  config.resolve.alias['mermaid-isomorphic'] = path.resolve(__dirname, 'node_modules/mermaid-isomorphic/dist/browser.js');
  return config
}
```
if using pnpm, also config the `.npmrc`: `public-hoist-pattern[]=mermaid-isomorphic`

**Comment by hariabinesh-l-4219** [comment]
This issue is due to exports field has a field browser, which is not preferred by module bundlers like webpack / rspack. To properly resolve this, add 

```js
conditionNames: ["browser", "..."],
```

to resolve filed.
https://webpack.js.org/configuration/resolve/#resolveconditionnames
https://rspack.rs/config/resolve#default-value

@remcohaszing 

Can you add browser field in package.json to solve this issue ?
