### ISSUE TITLE
The current browser implementation does not include the passed options to the create renderer factory

### ISSUE THREAD

**Issue by gionkunz** [remcohaszing/mermaid-isomorphic#8]
I've read in the comments the following:
```
This option is ignored in the browser. You need to call `mermaid.initialize()` manually.
```

I was wondering why you have made this decision? Because of unwanted side-effects and the unlucky nature or the mutable global properties of mermaid.initialize ?

**Comment by remcohaszing** [comment]
Yes, exactly that.
